---
kind: pipeline
type: docker
name: default

steps:
  - name: test
    image: cjsaylor/go-alpine-sdk:1.12
    commands:
      - go get -u golang.org/x/tools/cmd/cover
      - go test -mod=vendor -cover ./...
  - name: publish
    image: plugins/docker
    settings:
      repo: cjsaylor/chessbot
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      tags: latest
    when:
      branch: master
      event: push
      status: success
  - name: deploy
    image: appleboy/drone-ssh
    settings:
      host: box2.chris-saylor.com
      username: root
      port: 22
      script:
        - cd /root/chessbot && bash deploy.sh
      key:
        from_secret: ssh_key
    when:
      branch: master
      event: push
      status: success
